core/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('item/<slug>/', ItemDetail.as_view(), name='item-detail'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('order-summary/', OrderSummary.as_view(), name='order-summary'),
    path('add-coupon/', AddPromoCode.as_view(), name='add-promo-code'),
    path('remove-item-from-cart/<slug>/', minus_item_from_cart, name='remove-item-from-cart'),
    path('add-item-from-cart/<slug>/', plus_item_to_cart, name='add-item-from-cart'),
    path('delete-items-from-cart/<slug>/', delete_items_from_cart, name='delete_items_from_cart'),
    path('checkout/', CheckOut.as_view(), name='checkout'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('filter/<slug:slug>/', Filter.as_view(), name='filter'),
    path('search/', JsonFilterProductsView.as_view(), name='search'),
]

ecomelec/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
]

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField


class Category(models.Model):
    title = models.CharField(max_length=20)
    slug = models.SlugField()

    def __str__(self):
        return self.title


class Item(models.Model):
    LABEL_CHOICES = (
        ('P', 'primary'),
        ('S', 'secondary'),
        ('D', 'danger')
    )
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    description = models.TextField(null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('item-detail', kwargs={'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse('add-to-cart', kwargs={'slug': self.slug})

    def get_remove_from_cart_url(self):
        return reverse('remove-from-cart', kwargs={'slug': self.slug})


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.item.title

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_price(self):
        return self.quantity * self.item.discount_price

    def get_saving_price(self):
        return self.get_total_item_price() - self.get_total_discount_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(auto_now=True)
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)
    coupon_code = models.ForeignKey('Coupon', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon_code:
            total -= self.coupon_code.amount
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=30)
    amount = models.FloatField()

    def __str__(self):
        return self.code

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}

{% include 'navbar.html' %}

<body>
{% if messages %}
    <div class="pt-2">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    </div>
{% endif %}

{% block content %}
{% endblock %}
{% block extra_body %}
{% endblock %}
{% include 'footer.html' %}

{% include 'script.html' %}
</body>

</html>

templates/filter-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main>
        <div class="container">

            <!--Navbar-->
            <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

                <!-- Navbar brand -->
                <span class="navbar-brand">Categories:</span>

                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="basicExampleNav">

                    <!-- Links -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item" id="filter">
                            <a class="nav-link" href="/">All
                            </a>
                        </li>
                        {% for cat in categories %}
                            <li class="nav-item" id="filter">
                                <a class="nav-link" href="{% url 'filter' cat.slug %}">{{ cat.title }}</a>
                            </li>
                        {% endfor %}


                    </ul>
                    <!-- Links -->

                    <form class="form-inline" id="search-form" method="GET">
                        {% csrf_token %}
                        <div class="md-form my-0">
                            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search"
                                   id="search-input">
                        </div>

                    </form>
                </div>

            </nav>
            <div id="results" class="d-none">
                <section class="text-center mb-4">
                    <div class="row wow fadeIn" id="card"></div>
                </section>
            </div>
            <div id="resultbox">
                <div>
                    <section class="text-center mb-4">
                        <div class="row wow fadeIn">
                            {% for item in object_list %}
                                <div class="col-lg-3 col-md-6 mb-4">

                                    <div class="card">

                                        <div class="view overlay">
                                            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                                                 class="card-img-top"
                                                 alt="">
                                            <a href="{{ item.get_absolute_url }}">
                                                <div class="mask rgba-white-slight"></div>
                                            </a>
                                        </div>

                                        <div class="card-body text-center">
                                            <a href="" class="grey-text">
                                                <h5>{{ item.category.title }}</h5>
                                            </a>
                                            <h5>
                                                <strong>
                                                    <a href="{{ item.get_absolute_url }}"
                                                       class="dark-grey-text">{{ item.title }}
                                                        <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                                                    </a>
                                                </strong>
                                            </h5>

                                            <h4 class="font-weight-bold blue-text">
                                                <strong>
                                                    {% if item.discount_price %}
                                                        {{ item.discount_price }}
                                                    {% else %}
                                                        {{ item.price }}
                                                    {% endif %}$</strong>
                                            </h4>

                                        </div>

                                    </div>

                                </div>
                            {% endfor %}

                        </div>
                    </section>
                    {% if page_obj.has_other_pages %}
                        <nav class="d-flex justify-content-center wow fadeIn">
                            <ul class="pagination pg-blue">
                                {% if page_obj.has_previous %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                           aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                    </li>
                                {% endif %}


                                {% for p in page_obj.paginator.page_range %}
                                    {% if page_obj.number == p %}
                                        <li class="page-item active">
                                            <a class="page-link" href="#">{{ p }}
                                                <span class="sr-only">(current)</span>
                                            </a>
                                        </li>
                                    {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}"
                                           aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    {% endif %}
                </div>
            </div>

        </div>
    </main>
    <script>
        const url = window.location.href
        const searchForm = document.getElementById('search-form')
        const searchInput = document.getElementById('search-input')
        let resultsBox = document.getElementById('resultbox')
        let results = document.getElementById('results')
        let card = document.getElementById('card')
        const csrf = document.getElementsByName('csrfmiddlewaretoken')[0].value
        console.log(csrf)
        const sendSearchData = (item) => {
            $.ajax({
                type: 'GET',
                url: 'search/',
                data: {
                    'csrfmiddlewaretoken': csrf,
                    'item': item
                },
                success: (res) => {
                    console.log(res)
                    const data = res.data
                    if (Array.isArray(data)) {
                        data.forEach(item => {
                            resultsBox.classList.add('d-none')
                            results.classList.remove('d-none')
                            console.log(data)
                            card.innerHTML += `
                                <div class="col-lg-3 col-md-6 mb-4" >
                                    <div class="card">

                                        <div class="view overlay">
                                            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                                                 class="card-img-top"
                                                 alt="">
                                            <a href="${item.get_absolute_url}">
                                                <div class="mask rgba-white-slight"></div>
                                            </a>
                                        </div>

                                        <div class="card-body text-center">
                                            <a href="" class="grey-text">
                                                <h5>${item.category}</h5>
                                            </a>
                                            <h5>
                                                <strong>
                                                    <a href="${item.get_absolute_url}}"
                                                       class="dark-grey-text">${item.title}
                                                        <span class="badge badge-pill ${item.get_label_display}-color">NEW</span>
                                                    </a>
                                                </strong>
                                            </h5>

                                            <h4 class="font-weight-bold blue-text">
                                                <strong>
                                                    ${item.price}$</strong>
                                            </h4>

                                        </div>

                                    </div>
                                </div>
                            `
                        })
                    } else {
                        if (searchInput.value.length > 0) {
                            resultsBox.classList.add('d-none')
                            results.classList.remove('d-none')
                            card.innerHTML = `<b>${data}</b>`
                        }
                    }
                },
                error: (err) => {
                    console.log(err)
                }
            })
        }

        searchInput.addEventListener('keyup', e => {
            const result = e.target.value
            if (result.length === 0) {
                results.classList.add('d-none')
                resultsBox.classList.remove('d-none')
            }
            sendSearchData(result)
            card.innerHTML = ``

        })
    </script>
    <script>
        const allElementContainGrepperClassName = document.querySelectorAll('[id=filter]');
        let link = window.location.href.split('/');

        for (let i = 0; i < allElementContainGrepperClassName.length; i++) {
            let nameCategory = allElementContainGrepperClassName[i].getElementsByTagName('a')[0].innerHTML.toLowerCase();
            if (nameCategory === link[link.length-2]) {
                allElementContainGrepperClassName[i].classList.add('active')
            }
        }
    </script>
{% endblock %}

templates/footer.html
{% load static %}
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="https://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block head_title %}E-commerce{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <style type="text/css">
        html,
        body,
        header,
        .carousel {
            height: 60vh;
        }

        @media (max-width: 740px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }

        @media (min-width: 800px) and (max-width: 850px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }

    </style>
</head>

templates/home-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main>
        <div class="container">

            <!--Navbar-->
            <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

                <!-- Navbar brand -->
                <span class="navbar-brand">Categories:</span>

                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="basicExampleNav">

                    <!-- Links -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'home' %}">All</a>
                        </li>
                        {% for cat in categories %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'filter' cat.slug %}">{{ cat.title }}</a>
                            </li>
                        {% endfor %}


                    </ul>
                    <!-- Links -->

                    <form class="form-inline" id="search-form" method="GET" action="{% url 'search' %}">
                        {% csrf_token %}
                        <div class="md-form my-0">
                            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search"
                                   id="search-input">
                        </div>

                    </form>
                </div>

            </nav>
            <div id="results" class="d-none">
                <section class="text-center mb-4">
                    <div class="row wow fadeIn" id="card"></div>
                </section>
            </div>
            <div id="resultbox">
                <div>
                    <section class="text-center mb-4">
                        <div class="row wow fadeIn">
                            {% for item in object_list %}
                                <div class="col-lg-3 col-md-6 mb-4">

                                    <div class="card">

                                        <div class="view overlay">
                                            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                                                 class="card-img-top"
                                                 alt="">
                                            <a href="{{ item.get_absolute_url }}">
                                                <div class="mask rgba-white-slight"></div>
                                            </a>
                                        </div>

                                        <div class="card-body text-center">
                                            <a href="" class="grey-text">
                                                <h5>{{ item.category.title }}</h5>
                                            </a>
                                            <h5>
                                                <strong>
                                                    <a href="{{ item.get_absolute_url }}"
                                                       class="dark-grey-text">{{ item.title }}
                                                        <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                                                    </a>
                                                </strong>
                                            </h5>

                                            <h4 class="font-weight-bold blue-text">
                                                <strong>
                                                    {% if item.discount_price %}
                                                        {{ item.discount_price }}
                                                    {% else %}
                                                        {{ item.price }}
                                                    {% endif %}$</strong>
                                            </h4>

                                        </div>

                                    </div>

                                </div>
                            {% endfor %}

                        </div>
                    </section>
                    {% if page_obj.has_other_pages %}
                        <nav class="d-flex justify-content-center wow fadeIn">
                            <ul class="pagination pg-blue">
                                {% if page_obj.has_previous %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                           aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                    </li>
                                {% endif %}


                                {% for p in page_obj.paginator.page_range %}
                                    {% if page_obj.number == p %}
                                        <li class="page-item active">
                                            <a class="page-link" href="#">{{ p }}
                                                <span class="sr-only">(current)</span>
                                            </a>
                                        </li>
                                    {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}"
                                           aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    {% endif %}
                </div>
            </div>

        </div>
    </main>
    <script>
        const url = window.location.href
        const searchForm = document.getElementById('search-form')
        const searchInput = document.getElementById('search-input')
        let resultsBox = document.getElementById('resultbox')
        let results = document.getElementById('results')
        let card = document.getElementById('card')
        const csrf = document.getElementsByName('csrfmiddlewaretoken')[0].value
        console.log(csrf)
        const sendSearchData = (item) => {
            $.ajax({
                type: 'GET',
                url: 'search/',
                data: {
                    'csrfmiddlewaretoken': csrf,
                    'item': item
                },
                success: (res) => {
                    console.log(res)
                    const data = res.data
                    if (Array.isArray(data)) {
                        data.forEach(item => {
                            resultsBox.classList.add('d-none')
                            results.classList.remove('d-none')
                            console.log(data)
                            card.innerHTML += `
                                <div class="col-lg-3 col-md-6 mb-4" >
                                    <div class="card">

                                        <div class="view overlay">
                                            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                                                 class="card-img-top"
                                                 alt="">
                                            <a href="${item.get_absolute_url}">
                                                <div class="mask rgba-white-slight"></div>
                                            </a>
                                        </div>

                                        <div class="card-body text-center">
                                            <a href="" class="grey-text">
                                                <h5>${item.category}</h5>
                                            </a>
                                            <h5>
                                                <strong>
                                                    <a href="${item.get_absolute_url}}"
                                                       class="dark-grey-text">${item.title}
                                                        <span class="badge badge-pill ${item.get_label_display}-color">NEW</span>
                                                    </a>
                                                </strong>
                                            </h5>

                                            <h4 class="font-weight-bold blue-text">
                                                <strong>
                                                    ${item.price}$</strong>
                                            </h4>

                                        </div>

                                    </div>
                                </div>
                            `
                        })
                    } else {
                        if (searchInput.value.length > 0) {
                            resultsBox.classList.add('d-none')
                            results.classList.remove('d-none')
                            card.innerHTML = `<b>${data}</b>`
                        }
                    }
                },
                error: (err) => {
                    console.log(err)
                }
            })
        }

        searchInput.addEventListener('keyup', e => {
            const result = e.target.value
            if (result.length === 0) {
                results.classList.add('d-none')
                resultsBox.classList.remove('d-none')
            }
            sendSearchData(result)
            card.innerHTML = ``

        })
    </script>
{% endblock %}

templates/payment.html
{% extends 'base.html' %}

{% block content %}
        <main class="mt-2 pt-2">
        <div class="container wow fadeIn">

            <!-- Heading -->
            <h2 class="my-5 h2 text-center">Payment</h2>

            <!--Grid row-->
            <div class="row">

                <!--Grid column-->
                <div class="col-md-8 mb-4">
                </div>
            </div>
        </div>
        </main>
{% endblock %}

templates/script.html
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
    // Animations initialization
    new WOW().init();

</script>